spring:
  application:
    name: communication
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
  flyway:
    user: postgres
    password: postgres
    schemas: communication
    url: jdbc:postgresql://dbpostgresql:5432/communication
    enabled: true
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/communication
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 1

  jackson:
    deserialization:
      fail-on-unknown-properties: true
    default-property-inclusion: NON_NULL